---
application:
  name: "express-server"
  project: "Nodejs"
  organization: "QoveryCommunity"
  storage:
  - name: "Express"
    size: "10"
    type: "fast_ssd"
    mount_point: "/mnt/Express"
routers:
- name: "main-express-server"
  routes:
  - application_name: "express-server"
    paths:
    - "/*"
