---
application:
  name: "express-server"
  project: "random"
  organization: "QoveryCommunity",
  publicly_accessible: true
  port: 8080,
routers:
- name: "main-express-server"
  routes:
  - application_name: "express-server"
    paths:
    - "/*"
